runtime: nodejs18

env_variables:
  NODE_ENV: production
  # .env

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
  # Static assets (CSS, JS, images)
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))$
    static_files: dist/apps/auth-assessment/\1
    upload: dist/apps/auth-assessment/.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$
    secure: always

  # API routes
  - url: /api/.*
    script: auto
    secure: always

  # Frontend SPA routes (Angular)
  - url: /.*
    static_files: dist/apps/auth-assessment/index.html
    upload: dist/apps/auth-assessment/index.html
    secure: always
