runtime: nodejs20

env_variables:
  NODE_ENV: production
  MONGODB_URI: mongodb+srv://rawan:penny-db123@penny-db.rwe3jvs.mongodb.net/?retryWrites=true&w=majority&appName=penny-db
  JWT_SECRET: penny-secret-key-production-2024-very-secure-long-key
  JWT_EXPIRES_IN: 8h

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
